import { useEffect, useState } from 'react'
import { projectsApi, tasksApi, type Task, type Project } from '../lib/api'
import { PageHeader, Badge, Empty } from '../components/Ui'

export default function Tasks(){const [projects,setProjects]=useState<Project[]>([]);const [tasks,setTasks]=useState<(Task&{projectName:string})[]>([]);const [status,setStatus]=useState('');const [projectId,setProjectId]=useState('');
 useEffect(()=>{(async()=>{const r=await projectsApi.list({limit:100});setProjects(r.data.data)})()},[])
 useEffect(()=>{(async()=>{const target=projectId?projects.filter(p=>p.id===Number(projectId)):projects;const all:(Task&{projectName:string})[]=[];for(const p of target){try{const r=await projectsApi.tasks(p.id,status||undefined);all.push(...r.data.map(t=>({...t,projectName:p.name})))}catch{}}setTasks(all)})()},[projects,projectId,status])
 async function toggle(t:Task){const next=t.status==='DONE'?'TODO':t.status==='TODO'?'IN_PROGRESS':'DONE';await tasksApi.update(t.id,{status:next});setTasks(x=>x.map(a=>a.id===t.id?{...a,status:next}:a))}
 return <><PageHeader eyebrow="OPERATIONS" title="Tarefas" description="Acompanhe execução, status e responsabilidade em todo o workspace."/><div className="toolbar"><select value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">Todos os projetos</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Todos os status</option><option value="TODO">TODO</option><option value="IN_PROGRESS">IN PROGRESS</option><option value="DONE">DONE</option></select><span className="toolbar-meta">{tasks.length} tarefas</span></div><section className="task-grid">{tasks.length?tasks.map(t=><article className="task-card" key={t.id}><div className="task-top"><Badge tone={t.status==='DONE'?'success':t.status==='IN_PROGRESS'?'amber':''}>{t.status}</Badge><button className="icon-btn" onClick={()=>toggle(t)} title="Avançar status">↻</button></div><h3>{t.title}</h3><p>{t.description||'Sem descrição.'}</p><div className="task-foot"><span>{t.projectName}</span><small>#{t.id}</small></div></article>):<div className="panel task-empty"><Empty title="Nenhuma tarefa" description="As tarefas dos projetos aparecerão aqui."/></div>}</section></>
}
